apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: cli
  name: cli
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: cli
    spec:
      containers:
      - args:
        - /bin/bash
        - -c
        - './scripts/script.sh ; sleep '
        env:
        - name: GOPATH
          value: /opt/gopath
        - name: CORE_VM_ENDPOINT
          value: unix:///host/var/run/docker.sock
        - name: CORE_LOGGING_LEVEL
          value: DEBUG
        - name: CORE_PEER_ID
          value: cli
        - name: CORE_PEER_ADDRESS
          value: peer0.org1.example.com:7051
        - name: CORE_PEER_LOCALMSPID
          value: Org1MSP
        - name: CORE_PEER_TLS_ENABLED
          value: "true"
        - name: CORE_PEER_TLS_CERT_FILE
          value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt
        - name: CORE_PEER_TLS_KEY_FILE
          value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
        - name: CORE_PEER_MSPCONFIGPATH
          value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
        image: hyperledger/fabric-tools
        name: cli
        resources: {}
        tty: true
        volumeMounts:
        - mountPath: /etc/hosts
          name: cli-claim0
        - mountPath: /host/var/run/
          name: cli-claim1
        - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go
          name: cli-claim2
        - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
          name: cli-claim3
        - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
          name: cli-claim4
        - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
          name: cli-claim5
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
      restartPolicy: Always
      volumes:
      - name: cli-claim0
        persistentVolumeClaim:
          claimName: cli-claim0
      - name: cli-claim1
        persistentVolumeClaim:
          claimName: cli-claim1
      - name: cli-claim2
        persistentVolumeClaim:
          claimName: cli-claim2
      - name: cli-claim3
        persistentVolumeClaim:
          claimName: cli-claim3
      - name: cli-claim4
        persistentVolumeClaim:
          claimName: cli-claim4
      - name: cli-claim5
        persistentVolumeClaim:
          claimName: cli-claim5
status: {}
