kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: crypto-config-pvc
  namespace: fabric
spec:
#  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
