kind: PersistentVolume
apiVersion: v1
metadata:
  name: crypto-config-peer0-org1-pv
  namespace: fabric
  labels:
    type: local
spec:
#  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/oleks/bx_fabric/Separete_nodes/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com"
