kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mypvc
  namespace: fabric
spec:
#  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
