kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mypvc
  labels:
    type: local
  namespace: fabric
spec:
#  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
