apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: orderer
  name: orderer
spec:
  ports:
  - name: "7050"
    port: 7050
    targetPort: 7050
  selector:
    io.kompose.service: orderer
status:
  loadBalancer: {}
