apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: orderer
  name: orderer
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: orderer
    spec:
      containers:
      - args:
        - orderer
        env:
        - name: ORDERER_GENERAL_LOGLEVEL
          value: debug
        - name: ORDERER_GENERAL_LISTENADDRESS
          value: 0.0.0.0
        - name: ORDERER_GENERAL_GENESISMETHOD
          value: file
        - name: ORDERER_GENERAL_GENESISFILE
          value: /var/hyperledger/orderer/orderer.genesis.block
        - name: ORDERER_GENERAL_LOCALMSPID
          value: OrdererMSP
        - name: ORDERER_GENERAL_LOCALMSPDIR
          value: /var/hyperledger/orderer/msp
        - name: ORDERER_GENERAL_TLS_ENABLED
          value: "true"
        - name: ORDERER_GENERAL_TLS_PRIVATEKEY
          value: /var/hyperledger/orderer/tls/server.key
        - name: ORDERER_GENERAL_TLS_CERTIFICATE
          value: /var/hyperledger/orderer/tls/server.crt
        - name: ORDERER_GENERAL_TLS_ROOTCAS
          value: '[/var/hyperledger/orderer/tls/ca.crt]'
        image: hyperledger/fabric-orderer
        name: orderer-example-com
        ports:
        - containerPort: 7050
        resources: {}
        volumeMounts:
        - mountPath: /etc/hosts
          name: orderer-claim0
        - mountPath: /var/hyperledger/orderer/orderer.genesis.block
          name: orderer-claim1
        - mountPath: /var/hyperledger/orderer/msp
          name: orderer-claim2
        - mountPath: /var/hyperledger/orderer/tls
          name: orderer-claim3
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric
      restartPolicy: Always
      volumes:
      - name: orderer-claim0
        persistentVolumeClaim:
          claimName: orderer-claim0
      - name: orderer-claim1
        persistentVolumeClaim:
          claimName: orderer-claim1
      - name: orderer-claim2
        persistentVolumeClaim:
          claimName: orderer-claim2
      - name: orderer-claim3
        persistentVolumeClaim:
          claimName: orderer-claim3
status: {}
