apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: peer0-org1
  name: peer0-org1
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: peer0-org1
    spec:
      containers:
      - args:
        - peer
        - node
        - start
        env:
        - name: CORE_PEER_ID
          value: peer0.org1.example.com
        - name: CORE_PEER_ADDRESS
          value: peer0.org1.example.com:7051
        - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
          value: peer0.org1.example.com:7051
        - name: CORE_PEER_LOCALMSPID
          value: Org1MSP
        - name: CORE_VM_ENDPOINT
          value: unix:///host/var/run/docker.sock
        - name: CORE_LOGGING_LEVEL
          value: DEBUG
        - name: CORE_PEER_TLS_ENABLED
          value: "true"
        - name: CORE_PEER_GOSSIP_USELEADERELECTION
          value: "true"
        - name: CORE_PEER_GOSSIP_ORGLEADER
          value: "false"
        - name: CORE_PEER_PROFILE_ENABLED
          value: "true"
        - name: CORE_PEER_TLS_CERT_FILE
          value: /etc/hyperledger/fabric/tls/server.crt
        - name: CORE_PEER_TLS_KEY_FILE
          value: /etc/hyperledger/fabric/tls/server.key
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /etc/hyperledger/fabric/tls/ca.crt
        image: hyperledger/fabric-peer
        name: peer0-org1-example-com
        ports:
        - containerPort: 7051
        - containerPort: 7053
        resources: {}
        volumeMounts:
        - mountPath: /etc/hosts
          name: peer0-org1-claim0
        - mountPath: /host/var/run/
          name: peer0-org1-claim1
        - mountPath: /etc/hyperledger/fabric/msp
          name: peer0-org1-claim2
        - mountPath: /etc/hyperledger/fabric/tls
          name: peer0-org1-claim3
        - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations
          name: peer0-org1-claim4
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
      restartPolicy: Always
      volumes:
      - name: peer0-org1-claim0
        persistentVolumeClaim:
          claimName: peer0-org1-claim0
      - name: peer0-org1-claim1
        persistentVolumeClaim:
          claimName: peer0-org1-claim1
      - name: peer0-org1-claim2
        persistentVolumeClaim:
          claimName: peer0-org1-claim2
      - name: peer0-org1-claim3
        persistentVolumeClaim:
          claimName: peer0-org1-claim3
      - name: peer0-org1-claim4
        persistentVolumeClaim:
          claimName: peer0-org1-claim4
status: {}
