apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    service: peer1-org1-example-com
  name: peer1-org1-example-com
  namespace: fabric
spec:
  replicas: 1
  selector:
    service: peer1-org1-example-com
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: peer1-org1-example-com
    spec:
      containers:
      - command: ["/bin/sh", "-c", "chmod +x /root/start_peer.sh && /root/start_peer.sh"]
        env:
        - name: CORE_PEER_ID
          value: peer1.org1.example.com
        - name: CORE_PEER_ADDRESS
          value: peer1.org1.example.com:7051
        - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
          value: peer1.org1.example.com:7051
        - name: CORE_PEER_LOCALMSPID
          value: Org1MSP

        - name: CORE_VM_ENDPOINT
          value: unix:///host/var/run/docker.sock
        - name: CORE_LOGGING_LEVEL
          value: DEBUG
        - name: CORE_PEER_TLS_ENABLED
          value: "true"
        - name: CORE_PEER_GOSSIP_USELEADERELECTION
          value: "true"
        - name: CORE_PEER_GOSSIP_ORGLEADER
          value: "false"
        - name: CORE_PEER_PROFILE_ENABLED
          value: "true"

        - name: CORE_PEER_TLS_CERT_FILE
          value: /etc/hyperledger/fabric/tls/server.crt
        - name: CORE_PEER_TLS_KEY_FILE
          value: /etc/hyperledger/fabric/tls/server.key
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /etc/hyperledger/fabric/tls/ca.crt          
        image: hyperledger/fabric-peer:x86_64-1.0.1
        imagePullPolicy: ""
        name: peer1-org1-example-com
        volumeMounts:
        - name: msptls
          mountPath: /etc/fabric_crypto
        - name: start-peer
          mountPath: /root                  
        ports:
        - containerPort: 7051
        - containerPort: 7053
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      
      volumes:
      - name: msptls
        configMap:
          name: cc-peer1-org1
      - name: start-peer
        configMap:
          name: start-peer
      - name: varrun
        hostPath: 
          path: /var/run/
status:
  replicas: 0
