apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    service: cli
  name: cli
  namespace: fabric
spec:
  replicas: 1
  selector:
    service: cli
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: cli
    spec:
      containers:
      - command: ["/bin/sh", "-c", "./scripts/script.sh ${CHANNEL_NAME}; sleep $TIMEOUT"]
        env:
        - name: GOPATH
          value: /opt/gopath
        - name: CORE_VM_ENDPOINT
          value: unix:///host/var/run/docker.sock
        - name: CORE_LOGGING_LEVEL
          value: DEBUG
        - name: CORE_PEER_ID
          value: cli
        - name: CORE_PEER_ADDRESS
          value: peer0.org1.example.com:7051
        - name: CORE_PEER_LOCALMSPID
          value: Org1MSP
        - name: CORE_PEER_TLS_ENABLED
          value: true
        - name: CORE_PEER_TLS_CERT_FILE
          value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt
        - name: CORE_PEER_TLS_KEY_FILE
          value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
        - name: CORE_PEER_MSPCONFIGPATH
          value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
        image: hyperledger/fabric-tools
        imagePullPolicy: ""
        name: cli
        volumeMounts:
        - name: peer-cli-cm
          mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: peer-cli-vol
        configMap:
          name: peer-cli-cm
status:
  replicas: 0
