apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: orderer-example-com
  namespace: fabric
spec:
  type: NodePort
  ports:
   - name: "port1"
     nodePort: 0
     port: 7050
     protocol: ""
     targetPort: 0
  selector:
    service: orderer-example-com
status:
  loadBalancer: {}
